name: CI/CD Pipeline Project
on:
  push:
    branches:
      - master
jobs:
  build-java-app:
    name: Build and Deploy Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'coretto'
          java-version: 17

      - name: Build App
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USER_NAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_HUB_USER_NAME}}/myapp:1.0.0